WEAPONS = {
    "Dussack": {
        "tier": 1,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 0,
        "crit": 0,
        "dmg": 8,
    },
    "Keule": {
        "tier": 1,
        "consumable": 0,
        "targets": [1],
        "material": "",
        "acc": -10,
        "crit": 20,
        "dmg": 6,
    },
    "Knüppel": {
        "tier": 1,
        "consumable": 0,
        "targets": [1],
        "material": "",
        "acc": 0,
        "crit": 10,
        "dmg": 6,
    },
    "Beil": {
        "tier": 1,
        "consumable": 0,
        "targets": [1],
        "material": "",
        "acc": 0,
        "crit": 0,
        "dmg": 9,
    },
    "Spieß": {
        "tier": 1,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 10,
        "crit": 0,
        "dmg": 7,
    },
    "Wurfkeule": {
        "tier": 1,
        "consumable": 1,
        "targets": [1],
        "material": "",
        "acc": -40,
        "crit": 10,
        "dmg": 16,
    },
    "Wurfspieß": {
        "tier": 1,
        "consumable": 1,
        "targets": [1],
        "material": "metal",
        "acc": -30,
        "crit": 0,
        "dmg": 10,
    },
    "Hammer": {
        "tier": 1,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 0,
        "crit": 10,
        "dmg": 5,
    },
    "Messer": {
        "tier": 1,
        "consumable": 0,
        "targets": [1, 2],
        "material": "metal",
        "acc": 10,
        "crit": 5,
        "dmg": 3,
    },
    "Bauernsense": {
        "tier": 1,
        "consumable": 0,
        "targets": [-1],
        "material": "metal",
        "acc": 0,
        "crit": 0,
        "dmg": 4,
    },
    "Mistgabel": {
        "tier": 1,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 5,
        "crit": 5,
        "dmg": 6,
    },
    "Säbel": {
        "tier": 2,
        "consumable": 0,
        "targets": [-1],
        "material": "metal",
        "acc": 10,
        "crit": 0,
        "dmg": 10,
    },
    "Bogen": {
        "tier": 2,
        "consumable": 2,
        "targets": [1],
        "material": "",
        "acc": -20,
        "crit": 0,
        "dmg": 40,
    },
    "Dolchstab": {
        "tier": 2,
        "consumable": 0,
        "targets": [2],
        "material": "metal",
        "acc": 30,
        "crit": 5,
        "dmg": 8,
    },
    "Antennendolch": {
        "tier": 2,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 20,
        "crit": 5,
        "dmg": 16,
    },
    "Kriegsgabel": {
        "tier": 2,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 10,
        "crit": 0,
        "dmg": 20,
    },
    "Sturmsense": {
        "tier": 2,
        "consumable": 0,
        "targets": [-1],
        "material": "metal",
        "acc": 0,
        "crit": 0,
        "dmg": 12,
    },
    "Streithacke": {
        "tier": 2,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 60,
        "crit": 0,
        "dmg": 10,
    },
    "Holzfäller Axt": {
        "tier": 2,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 0,
        "crit": 0,
        "dmg": 29,
    },
    "Dolch": {
        "tier": 2,
        "consumable": 0,
        "targets": [1, -1],
        "material": "metal",
        "acc": 10,
        "crit": 5,
        "dmg": 25,
    },
    "Wurfspeer": {
        "tier": 2,
        "consumable": 1,
        "targets": [1],
        "material": "metal",
        "acc": -30,
        "crit": 0,
        "dmg": 35,
    },
    "Degen": {
        "tier": 3,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 10,
        "crit": 0,
        "dmg": 60,
    },
    "Hornbogen": {
        "tier": 3,
        "consumable": 2,
        "targets": [1],
        "material": "",
        "acc": -15,
        "crit": 0,
        "dmg": 130,
    },
    "Gladius": {
        "tier": 3,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 0,
        "crit": 0,
        "dmg": 80,
    },
    "Kriegshammer": {
        "tier": 3,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 0,
        "crit": 10,
        "dmg": 50,
    },
    "Lanze": {
        "tier": 3,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 30,
        "crit": 0,
        "dmg": 45,
    },
    "Kriegszepter": {
        "tier": 3,
        "consumable": 0,
        "targets": [1, -1],
        "material": "metal",
        "acc": 10,
        "crit": 5,
        "dmg": 35,
    },
    "Mordaxt": {
        "tier": 3,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": -20,
        "crit": 0,
        "dmg": 100,
    },
    "Armbrust": {
        "tier": 4,
        "consumable": 2,
        "targets": [1],
        "material": "metal",
        "acc": -10,
        "crit": 10,
        "dmg": 400,
    },
    "Streitkolben": {
        "tier": 4,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 0,
        "crit": 5,
        "dmg": 300,
    },
    "Streithammer": {
        "tier": 4,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 0,
        "crit": 10,
        "dmg": 260,
    },
    "Triangulärer Vollgriffdolch": {
        "tier": 4,
        "consumable": 0,
        "targets": [1, -1],
        "material": "metal",
        "acc": 40,
        "crit": 5,
        "dmg": 220,
    },
    "Fausthammer": {
        "tier": 4,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 0,
        "crit": 10,
        "dmg": 340,
    },
    "Langschwert": {
        "tier": 4,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 0,
        "crit": 0,
        "dmg": 360,
    },
    "Schießeisen": {
        "tier": 5,
        "consumable": 2,
        "targets": [1],
        "material": "metal",
        "acc": -10,
        "crit": 0,
        "dmg": 1300,
    },
    "Wurfsterne": {
        "tier": 5,
        "consumable": 1,
        "targets": [1, -1],
        "material": "metal",
        "acc": -20,
        "crit": 0,
        "dmg": 700,
    },
    "Xiphos": {
        "tier": 5,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": -100,
        "crit": -30,
        "dmg": 2500,
    },
    "Streitaxt": {
        "tier": 5,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 0,
        "crit": 0,
        "dmg": 800,
    },
    "Morgenstern": {
        "tier": 5,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 0,
        "crit": 60,
        "dmg": 300,
    },
    "Griffangelschwert": {
        "tier": 5,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": 50,
        "crit": -10,
        "dmg": 699,
    },
    "Griffzungenschwert": {
        "tier": 5,
        "consumable": 0,
        "targets": [1],
        "material": "metal",
        "acc": -30,
        "crit": 20,
        "dmg": 701,
    },
}

MOB_BASE_STATS = {
    "Bär": {
        "health": 7,
        "armor": 0,
        "dodge": 10,
        "dmg": 3,
        "acc": 70,
        "crit": 0,
        "ls": 0,
        "xp": 10,
        "level-range": range(1, 4),
        "gender": "M",
    },
    "Wolf": {
        "health": 4,
        "armor": 0,
        "dodge": 10,
        "dmg": 5,
        "acc": 70,
        "crit": 0,
        "ls": 0,
        "xp": 10,
        "level-range": range(1, 4),
        "gender": "M",
    },
    "skelett": {
        "health": 40,
        "armor": 0,
        "dodge": 10,
        "dmg": 0,
        "acc": 0,
        "crit": 0,
        "ls": 0,
        "xp": 0,
        "level-range": range(4, 10),
        "gender": "N",
    },
    "gnom": {
        "health": 100,
        "armor": 0,
        "dodge": 20,
        "dmg": 0,
        "acc": 0,
        "crit": 0,
        "ls": 0,
        "xp": 0,
        "level-range": range(6, 16),
        "gender": "M",
    },
    "kobold": {
        "health": 0,
        "armor": 0,
        "dodge": 0,
        "dmg": 0,
        "acc": 0,
        "crit": 0,
        "ls": 0,
        "xp": 0,
        "level-range": range(10, 16),
        "gender": "M",
    },
    "gespenst": {
        "health": 0,
        "armor": 0,
        "dodge": 0,
        "dmg": 0,
        "acc": 0,
        "crit": 0,
        "ls": 0,
        "xp": 0,
        "level-range": range(16, 26),
        "gender": "N",
    },
    "ghul": {
        "health": 0,
        "armor": 0,
        "dodge": 0,
        "dmg": 0,
        "acc": 0,
        "crit": 0,
        "ls": 0,
        "level-range": range(16, 26),
        "gender": "M",
    },
    "ork": {
        "health": 0,
        "armor": 0,
        "dodge": 0,
        "dmg": 0,
        "acc": 0,
        "crit": 0,
        "ls": 0,
        "xp": 0,
        "level-range": range(26, 36),
        "gender": "M",
    },
    "troll": {
        "health": 0,
        "armor": 0,
        "dodge": 0,
        "dmg": 0,
        "acc": 0,
        "crit": 0,
        "ls": 0,
        "xp": 0,
        "level-range": range(26, 36),
        "gender": "M",
    },
    "vampir": {
        "health": 0,
        "armor": 0,
        "dodge": 0,
        "dmg": 0,
        "acc": 0,
        "crit": 0,
        "ls": 0,
        "xp": 0,
        "level-range": range(36, 46),
        "gender": "M",
    },
    "banshee": {
        "health": 0,
        "armor": 0,
        "dodge": 0,
        "dmg": 0,
        "acc": 0,
        "crit": 0,
        "ls": 0,
        "xp": 0,
        "level-range": range(36, 46),
        "gender": "F",
    },
    "harpyie": {
        "health": 0,
        "armor": 0,
        "dodge": 0,
        "dmg": 0,
        "acc": 0,
        "crit": 0,
        "ls": 0,
        "xp": 0,
        "level-range": range(46, 56),
        "gender": "F",
    },
    "gargoyle": {
        "health": 0,
        "armor": 0,
        "dodge": 0,
        "dmg": 0,
        "acc": 0,
        "crit": 0,
        "ls": 0,
        "xp": 0,
        "level-range": range(46, 56),
        "gender": "M",
    },
}

PLAYER_BASE_STATS = {
        "health": 60,
        "armor": 0,
        "dodge": 5,
        "dmg": 2,
        "acc": 80,
        "crit": 5,
        "ls": 0,
}

PLAYER_BASE_STAT_INCREASE = {
        "health": 20,
        "armor": 0,
        "dodge": 1,
        "dmg": 1,
        "acc": 1,
        "crit": 1,
        "ls": 0,
}
