ANSI_BLACK = "\u001b[30m"
ANSI_RED = "\u001b[31m"
ANSI_GREEN = "\u001b[32m"
ANSI_YELLOW = "\u001b[33m"
ANSI_BLUE = "\u001b[34m"
ANSI_MAGENTA = "\u001b[35m"
ANSI_CYAN = "\u001b[36m"
ANSI_WHITE = "\u001b[37m"

ANSI_BRIGHT_BLACK = "\u001b[30;1m"
ANSI_BRIGHT_RED = "\u001b[31;1m"
ANSI_BRIGHT_GREEN = "\u001b[32;1m"
ANSI_BRIGHT_YELLOW = "\u001b[33;1m"
ANSI_BRIGHT_BLUE = "\u001b[34;1m"
ANSI_BRIGHT_MAGENTA = "\u001b[35;1m"
ANSI_BRIGHT_CYAN = "\u001b[36;1m"
ANSI_BRIGHT_WHITE = "\u001b[37;1m"

ANSI_RESET = "\u001b[0m"

ANSI_BOLD = "\u001b[1m"
ANSI_UNDERLINE = "\u001b[4m"
ANSI_REVERSED = "\u001b[7m"


def bold(text):
    return ANSI_BOLD + text + ANSI_RESET


def underline(text):
    return ANSI_UNDERLINE + text + ANSI_RESET


def reverse(text):
    return ANSI_REVERSED + text + ANSI_RESET


ANSI_ALL = [
    ANSI_BLACK,
    ANSI_RED,
    ANSI_GREEN,
    ANSI_YELLOW,
    ANSI_BLUE,
    ANSI_MAGENTA,
    ANSI_CYAN,
    ANSI_WHITE,
    ANSI_BRIGHT_BLACK,
    ANSI_BRIGHT_RED,
    ANSI_BRIGHT_GREEN,
    ANSI_BRIGHT_YELLOW,
    ANSI_BRIGHT_BLUE,
    ANSI_BRIGHT_MAGENTA,
    ANSI_BRIGHT_CYAN,
    ANSI_BRIGHT_WHITE,
    ANSI_RESET,
    ANSI_BOLD,
    ANSI_UNDERLINE,
    ANSI_REVERSED,
]
